name: Auto Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to owner
        uses: actions/github-script@v9
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.issue.number;

            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number,
              assignees: ["richardgong1987"]
            });